module.exports = {
    windowIndex: 3,
    closeButton: '#app > div > div.header > div:nth-child(2) > div.buttons > div.close_win > span > i',
    //roomListMenuIcon: '#roomListMenuIcon',
    roomListMenuIcon: '#app > div > div.header > div:nth-child(2) > div.layout.row.wrap.justify-center.align-center > div:nth-child(1) > i',
    //settingsMenuIcon: '#settingsMenuIcon',
    settingsMenuIcon: '#app > div > div.header > div:nth-child(2) > div.layout.row.wrap.justify-center.align-center > div:nth-child(2) > i',
    currentRoomName: "#currentRoomName",
    //micButton: '#micButton',
    micButton: '#app > div > footer > v-row > button:nth-child(1)',
    //micStatusIcon: '#micStatusIcon.icon.icon.icon-mic-off',
    micStatusIcon: '',
    //micStatusOffIcon: '#micStatusIcon.icon.icon.icon-mic-off',
    micStatusOffIcon: '#app > div > footer > v-row > button:nth-child(1) > div > div > i',   
    //micStatusOnIcon: '#micStatusIcon.icon.icon.icon-mic-on',
    micStatusOnIcon: '#app > div > footer > v-row > button.control_btn.control_on.btn > div > div > i',    
    //screenShareButton: '#screenShareButton',
    screenShareButton: '#app > div > footer > v-row > button:nth-child(2)',
    //screenShareStatusIcon: '#screenShareStatusIcon',
    screenShareStatusIcon: '',
    //screenshareSTatusOffIcon: '#screenShareStatusIcon.icon.icon.icon-screen-off',
    screenshareSTatusOffIcon: '#app > div > footer > v-row > button:nth-child(2) > div > div > i',
    //screenshareSTatusOnIcon: '#screenShareStatusIcon.icon.icon.icon-screen-off'
    screenshareSTatusOnIcon: '#app > div > footer > v-row > button.control_btn.control_on.btn.btn--flat > div > div > i'    
}