module.exports = {
    windowIndex : 3,
    messageBoxButton: '#myStatus > div.header_userProfile > div.shoulder_btn > span > span > span > button',
    avatarNoPhoto: '#myStatus > div.header_userProfile > div.avatar.small_avatar.teal.lighten-5 > div',
    avatar: '',
    name: '#myStatus > div.header_userProfile > div.my_name',
    statusIcon: '#myStatus > div.header_userProfile > div.member_profile_status > div.member_icon > i',
    currentStatus: '#myStatus > div.header_userProfile > div.member_profile_status > div.status_summary',
    statusTime: '',
    muteButton: '#myStatus > div.volume_control > div.volume_off',
    muteOffButton: '#myStatus > div.volume_control > div.volume_on',
    statusDropDownButton: '#myStatus > div:nth-child(4) > div.menu.drop_down_menu > div > div > div',
    statusDropDownText: '#myStatus > div:nth-child(4) > div.menu.drop_down_menu > div > div > div > div.drop_down_text',
    statusLetsTalk: '#app > div.menu__content.menuable__content__active > div > div:nth-child(1) > a > div > div',
    statusOutForMeal: '#app > div.menu__content.menuable__content__active > div > div:nth-child(2) > a > div > div',
    statusInAMeeting: '#app > div.menu__content.menuable__content__active > div > div:nth-child(3) > a > div > div',
    statusGoneOut: '#app > div.menu__content.menuable__content__active > div > div:nth-child(4) > a > div > div',
    statusSick: '#app > div.menu__content.menuable__content__active > div > div:nth-child(5) > a > div > div',
    statusWorkFromHome: '#app > div.menu__content.menuable__content__active > div > div:nth-child(2) > a > div > div',
    statusOnLeave: '#app > div.menu__content.menuable__content__active > div > div:nth-child(2) > a > div > div',
    clearStatus: '#myStatus > div:nth-child(4) > div:nth-child(2) > button',
    statusTimeDropDownButton: '#myStatus > div:nth-child(5) > div.menu.drop_down_menu > div > div > div',
    statusTimeDropDownText: '#myStatus > div:nth-child(5) > div.menu.drop_down_menu > div > div > div > div.drop_down_text',
    setToBusyButton: '#myStatus > div:nth-child(5) > div:nth-child(2) > span > span > span > button',
    calenderStatus: '#myStatus > div:nth-child(6) > div > div > div > i',
    calendarSettingsButton: '#myStatus > div:nth-child(6) > div > button'
}